sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
git:
  depth: 10
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm set loglevel error"
  - "npm set progress false"
  - "npm install -g npm@\"^2.0.0\""
script:
  - "npm test"
after_script:
  - "istanbul cover --verbose --dir coverage tests/tests.js && cat coverage/lcov.info | coveralls"
