sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
git:
  depth: 10
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm set loglevel error"
  - "npm set progress false"
  - "npm install -g npm@\"^2.0.0\""
script:
  - "npm test"
after_script:
  - "npm run coverage && codecov"
